# -*- coding: utf-8 -*-
"""OSM Quick 3D Settings Dock Widget.

Allows live styling, height adjustments, label toggles, and base slab depth
modifications on native QGIS layers generated by the plugin.
"""
from __future__ import annotations

from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import (
    QCheckBox,
    QComboBox,
    QDoubleSpinBox,
    QFormLayout,
    QFrame,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QPushButton,
    QScrollArea,
    QVBoxLayout,
    QWidget,
    QDockWidget,
)
from qgis.core import QgsProject, QgsLayerTreeGroup, QgsLayerTreeLayer, QgsSettings

from . import native3d, styling
from .osm_download import BASE_DEPTH_M

_S = "osm_quick_3d"


class PluginDockWidget(QDockWidget):
    def __init__(self, iface, parent=None):
        super().__init__("OSM Quick 3D Controller", parent)
        self.iface = iface
        self.setObjectName("OSMQuick3DController")
        self.setAllowedAreas(Qt.DockWidgetArea.LeftDockWidgetArea | Qt.DockWidgetArea.RightDockWidgetArea)
        
        self._build_ui()
        
        # Restore saved resolution settings
        s = QgsSettings()
        try:
            res_val = int(s.value(f"{_S}/map_resolution", 1024))
            ridx = self.map_resolution.findData(res_val)
            if ridx >= 0:
                self.map_resolution.blockSignals(True)
                self.map_resolution.setCurrentIndex(ridx)
                self.map_resolution.blockSignals(False)
        except (TypeError, ValueError):
            pass
        try:
            class_val = s.value(f"{_S}/classification", "continuous")
            clidx = self.classification.findData(class_val)
            if clidx >= 0:
                self.classification.blockSignals(True)
                self.classification.setCurrentIndex(clidx)
                self.classification.blockSignals(False)
        except (TypeError, ValueError):
            pass
            
        self.refresh_groups()
        
    _QSS = """
    QDockWidget {
        background: #eef1f2;
    }
    QGroupBox {
        font-weight: 600;
        font-size: 11px;
        color: #34474a;
        border: 1px solid #e0e5e6;
        border-radius: 8px;
        margin-top: 10px;
        padding: 8px;
        background: #ffffff;
    }
    QGroupBox::title {
        subcontrol-origin: margin;
        subcontrol-position: top left;
        left: 8px;
        top: 2px;
        padding: 0 4px;
        color: #5d7174;
        background: transparent;
    }
    QLabel { color: #3c4749; background: transparent; font-size: 11px; }
    QCheckBox { spacing: 6px; padding: 2px 0; color: #34474a; background: transparent; font-size: 11px; }
    QCheckBox::indicator { width: 14px; height: 14px; }
    QComboBox, QDoubleSpinBox {
        border: 1px solid #d2d9da;
        border-radius: 6px;
        padding: 3px 5px;
        background: #fbfcfc;
        min-height: 18px;
        font-size: 11px;
    }
    QComboBox:hover, QDoubleSpinBox:hover { border-color: #9cc3bf; }
    QComboBox:focus, QDoubleSpinBox:focus { border-color: #3f8079; background: #ffffff; }
    QPushButton {
        border-radius: 6px; padding: 4px 10px;
        background: #eef1f2; border: 1px solid #d2d9da; color: #34474a;
        font-size: 11px;
    }
    QPushButton:hover { background: #e4e9ea; }
    """

    def _build_ui(self):
        self.setStyleSheet(self._QSS)
        
        main_widget = QWidget()
        main_layout = QVBoxLayout(main_widget)
        main_layout.setContentsMargins(0, 0, 0, 0)
        main_layout.setSpacing(0)

        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QFrame.Shape.NoFrame)
        scroll.setStyleSheet("background: transparent;")

        container = QWidget()
        container.setStyleSheet("background: transparent;")
        root = QVBoxLayout(container)
        root.setContentsMargins(8, 8, 8, 8)
        root.setSpacing(8)

        # Target selection
        target_box = QGroupBox("Target city group")
        target_layout = QHBoxLayout(target_box)
        self.group_combo = QComboBox()
        self.group_combo.currentIndexChanged.connect(self._on_group_selected)
        self.refresh_btn = QPushButton("Refresh")
        self.refresh_btn.clicked.connect(self.refresh_groups)
        target_layout.addWidget(self.group_combo, 1)
        target_layout.addWidget(self.refresh_btn)
        root.addWidget(target_box)

        # Style & Settings controls
        settings_box = QGroupBox("Live styling")
        form = QFormLayout(settings_box)

        self.height_scale = QDoubleSpinBox()
        self.height_scale.setRange(0.5, 5.0)
        self.height_scale.setSingleStep(0.25)
        self.height_scale.setValue(1.0)
        self.height_scale.setSuffix("×")
        self.height_scale.valueChanged.connect(self._apply_changes)
        form.addRow("Height exaggeration:", self.height_scale)

        self.building_color = QComboBox()
        for value, label in styling.BUILDING_COLOR_MODES:
            self.building_color.addItem(label, value)
        self.building_color.currentIndexChanged.connect(self._update_color_preview)
        self.building_color.currentIndexChanged.connect(self._update_classification_enabled)
        self.building_color.currentIndexChanged.connect(self._apply_changes)
        form.addRow("Building colours:", self.building_color)

        self.classification = QComboBox()
        self.classification.addItem("Continuous (smooth)", "continuous")
        self.classification.addItem("Discrete intervals (equal)", "discrete")
        self.classification.addItem("Quantile (typical heights)", "quantile")
        self.classification.currentIndexChanged.connect(self._apply_changes)
        form.addRow("Color classification:", self.classification)

        self.color_preview = QFrame()
        self.color_preview.setFixedHeight(12)
        form.addRow("", self.color_preview)

        root.addWidget(settings_box)

        # Advanced Style controls
        adv_box = QGroupBox("Advanced style")
        adv_form = QFormLayout(adv_box)

        self.cb_labels = QCheckBox("Show name labels")
        self.cb_labels.toggled.connect(self._apply_changes)
        adv_form.addRow("", self.cb_labels)

        self.cb_base = QCheckBox("Extrude ground base plinth")
        self.cb_base.toggled.connect(self.cb_base.setEnabled) # dummy check
        self.cb_base.toggled.connect(self._apply_changes)
        adv_form.addRow("", self.cb_base)

        self.map_resolution = QComboBox()
        self.map_resolution.addItem("Low (256 px)", 256)
        self.map_resolution.addItem("Medium (512 px)", 512)
        self.map_resolution.addItem("High (1024 px)", 1024)
        self.map_resolution.addItem("Ultra (2048 px)", 2048)
        self.map_resolution.addItem("Insane (4096 px)", 4096)
        self.map_resolution.currentIndexChanged.connect(self._apply_resolution)
        adv_form.addRow("Map resolution (3D):", self.map_resolution)

        root.addWidget(adv_box)
        root.addStretch(1)

        scroll.setWidget(container)
        main_layout.addWidget(scroll)
        self.setWidget(main_widget)

    def refresh_groups(self):
        self.group_combo.blockSignals(True)
        self.group_combo.clear()
        
        root = QgsProject.instance().layerTreeRoot()
        for child in root.children():
            if isinstance(child, QgsLayerTreeGroup) and child.name().startswith("OSM Quick 3D —"):
                self.group_combo.addItem(child.name(), child)
                
        self.group_combo.blockSignals(False)
        self._on_group_selected()

    def _on_group_selected(self):
        group_node = self.group_combo.currentData()
        if not group_node:
            self.height_scale.setEnabled(False)
            self.building_color.setEnabled(False)
            self.cb_labels.setEnabled(False)
            self.cb_base.setEnabled(False)
            return

        self.height_scale.setEnabled(True)
        self.building_color.setEnabled(True)
        self.cb_labels.setEnabled(True)
        self.cb_base.setEnabled(True)

        # Read current state from the layers and configure UI
        layers = self._get_layers(group_node)
        buildings = layers.get("buildings")
        if buildings:
            # Detect height exaggeration from 3D renderer settings if possible
            r3d = buildings.renderer3D()
            if r3d:
                symbol = r3d.symbol()
                prop_key = getattr(symbol, "PropertyExtrusionHeight", None)
                if prop_key is not None:
                    prop = symbol.dataDefinedProperties().property(prop_key)
                    if prop and prop.isActive():
                        expr = prop.expressionString()
                        if "*" in expr:
                            try:
                                scale = float(expr.split("*")[-1].strip())
                                self.height_scale.blockSignals(True)
                                self.height_scale.setValue(scale)
                                self.height_scale.blockSignals(False)
                            except ValueError:
                                pass

            # Detect labels state
            self.cb_labels.blockSignals(True)
            self.cb_labels.setChecked(buildings.labelsEnabled())
            self.cb_labels.blockSignals(False)

        base = layers.get("base")
        if base:
            self.cb_base.blockSignals(True)
            self.cb_base.setChecked(base.renderer3D() is not None)
            self.cb_base.blockSignals(False)

        self._update_color_preview()

    def _get_layers(self, group_node) -> dict:
        layers = {}
        for child in group_node.children():
            if isinstance(child, QgsLayerTreeLayer):
                layer = child.layer()
                if layer:
                    name = layer.name()
                    if name == "OSM Buildings":
                        layers["buildings"] = layer
                    elif name == "OSM Roads":
                        layers["roads"] = layer
                    elif name == "OSM Base":
                        layers["base"] = layer
                    elif name == "OSM Base 3D":
                        layers["base_3d"] = layer
        return layers

    def _update_color_preview(self):
        stops = styling.building_color_swatches(self.building_color.currentData())
        if not stops:
            return
        if len(stops) == 1:
            stops = stops * 2
        n = len(stops) - 1
        parts = ", ".join(f"stop:{i / n:.4f} {hexv}" for i, hexv in enumerate(stops))
        self.color_preview.setStyleSheet(
            "QFrame{border:1px solid #d2d9da;border-radius:6px;"
            f"background:qlineargradient(x1:0,y1:0,x2:1,y2:0,{parts});}}"
        )

    def _apply_changes(self):
        group_node = self.group_combo.currentData()
        if not group_node:
            return

        layers = self._get_layers(group_node)
        buildings = layers.get("buildings")
        roads = layers.get("roads")
        base = layers.get("base")

        color_mode = self.building_color.currentData()
        classification = self.classification.currentData()
        scale = self.height_scale.value()
        want_labels = self.cb_labels.isChecked()
        want_base = self.cb_base.isChecked()

        if buildings:
            # Update 2D styling
            styling.style_buildings(buildings, color_mode, classification=classification)
            
            # Update 3D extrusion
            native3d.apply_building_extrusion(
                buildings,
                color_hex=styling.building_base_color(color_mode),
                height_scale=scale,
                color_expr=styling.building_color_expression(color_mode, classification=classification)
            )

            # Update Labels
            if want_labels:
                styling.label_by_name(buildings, size=8.0)
            else:
                buildings.setLabeling(None)
                buildings.setLabelsEnabled(False)
                buildings.triggerRepaint()

        if roads:
            if want_labels:
                styling.label_by_name(roads, size=7.5)
            else:
                roads.setLabeling(None)
                roads.setLabelsEnabled(False)
                roads.triggerRepaint()

        if base:
            transparent_val = base.customProperty("osm_quick_3d/transparent")
            transparent = str(transparent_val).strip().lower() in ("true", "1", "yes", "on")
            bg_color_hex = self.iface.mapCanvas().canvasColor().name()
            styling.style_base(base, color_mode, transparent=transparent, bg_color_hex=bg_color_hex)
            
        if want_base:
            if not base_3d and base:
                try:
                    base_3d = base.clone()
                    base_3d.setName("OSM Base 3D")
                    styling.style_base_3d_2d(base_3d)
                    QgsProject.instance().addMapLayer(base_3d, False)
                    group_node.insertLayer(len(group_node.children()), base_3d)
                except Exception:
                    pass
            if base_3d:
                native3d.apply_base_slab(
                    base_3d, depth=BASE_DEPTH_M, color_hex=styling.base_color_hex(color_mode))
        else:
            if base_3d:
                base_3d.setRenderer3D(None)
                base_3d.triggerRepaint()

        self.iface.mapCanvas().refresh()

    def _apply_resolution(self):
        res = self.map_resolution.currentData()
        if res:
            native3d.set_3d_map_tile_resolution(self.iface, res)
            s = QgsSettings()
            s.setValue(f"{_S}/map_resolution", res)

    def _update_classification_enabled(self):
        mode = self.building_color.currentData()
        is_ramp = mode != styling.BUILDING_COLOR_FUNCTION
        self.classification.setEnabled(is_ramp)
